---
- name: Deploy application
  hosts: all
  become: yes
  vars:
    image_tag: "{{ image_tag | default('latest') }}"
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "motbot/motbotmotbot:{{ image_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: runalpine
        image: "motbot/motbotmotbot:{{ image_tag }}"
        state: started
        ports:
          - "80:80" 
        restart_policy: always
